#!/bin/bash
# href: https://docs.docker.com/docker-cloud/builds/advanced/

echo "### Listing remote branches:"
git for-each-ref --format "%(refname:strip=3)" refs/remotes/origin/

# TODO: Keep the grep below up-to-date if more branches are created
latest=$(git for-each-ref --format "%(refname:strip=3)" refs/remotes/origin/ \
  | grep -v -e '^HEAD$' -e '^master$' -e 'dev' -e 'beta' -e 'alpha' \
  | cut -d '-' -f 1 | sort -V -u | tail -n1)

prefix=$(cut -d '-' -f 1 <<< "${SOURCE_BRANCH}")
# Get the (2|3)-dot prefix if applicable (otherwise the whole string)
# 8.11.0 => prefix=8.11.0
# 8.11.0-ocaml-4.09.0-flambda => prefix=8.11.0
# 8.12-alpha => prefix=8.12
# 8.12-alpha-ocaml-4.09.0-flambda => prefix=8.12  # 2-dot prefix
# dev => prefix=dev                               # the whole string

if [[ "$prefix" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    # 3-dot prefix => stable version
    minor=${prefix%.*}
    target=${SOURCE_BRANCH/#$prefix/$minor}
    echo "### Do additional docker push ($DOCKER_REPO:$target)"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$target"
    docker push "$DOCKER_REPO:$target"
elif [[ "$prefix" =~ ^[0-9]+\.[0-9]+$ ]]; then
    # 2-dot prefix => alpha/beta version
    ## remark: old regex: ^[0-9]+\.[0-9]+-[A-Za-z0-9]+$
    target=$(sed -e 's/\(-alpha\|-beta\)//' <<< "${SOURCE_BRANCH}")
    echo "### Do additional docker push ($DOCKER_REPO:$target)"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:$target"
    docker push "$DOCKER_REPO:$target"
fi

echo "### Latest stable branch is: $latest"

if [ "$SOURCE_BRANCH" = "$latest" ]; then
    echo "### Do additional docker push ($DOCKER_REPO:latest)"
    docker tag "$IMAGE_NAME" "$DOCKER_REPO:latest"
    docker push "$DOCKER_REPO:latest"
else
    echo "### no additional docker push"
fi
